name: 'Untested Code Annotations'
description: 'TODO'
author: 'TODO'
inputs:
  format:
    required: true
    description: 'The format of the code coverage files.'
  coverage-path:
    required: true
    description: 'The location of the generated code coverage files.'
runs:
  using: 'node16'
  main: 'dist/index.js'
